server:
  port: 8080
  servlet:
    context-path: /
spring:
  devtools:
    remote:
      restart:
        enabled: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates
    encoding: UTF-8
    suffix: .html
    mode: LEGACYHTML5
  datasource:
    url: jdbc:mysql://10.10.8.13:3309/test01?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: xdata123
    driver-class-name: com.mysql.jdbc.Driver
    #使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    #监控统计拦截的filters
    filters: stat
    #配置初始化大小/最小/最大
    initial-size: 1
    min-idle: 1
    max-active: 20
    #获取连接等待超时时间
    max-wait: 60000
    #间隔多久进行一次检测，检测需要关闭的空闲连接
    time-between-eviction-runs-millis: 60000
    #一个连接在池中最小生存的时间
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 'x'
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
    pool-prepared-statements: false
    max-pool-prepared-statement-per-connection-size: 20

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lys.lys_admin_api.module.demo.sys.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check
logging:
  level.com.lys.mapper: debug
  file: D:/lys.log


websocket:
  hostName: localhost
  port: 9096
  upgradeTimeout: 10000
  pingInterval: 25000
  pingTimeout: 180000